import type { OriginFacility } from "./types";

/** Publicly documented OS Hub records, plus well-known apparel/textile sites from public disclosures. OS IDs only where OS Hub published them. */
export const ORIGIN_INDEX: OriginFacility[] = [
  {
    osId: "IN2021079TDH72D",
    name: "YK Creation",
    address: "SM Road, Jalahalli West, Bengaluru, Karnataka",
    countryCode: "IN",
    countryName: "India",
    lat: 13.0454318,
    lng: 77.5218658,
    sectors: ["Apparel"],
    productTypes: ["Bottoms"],
    claimed: true,
  },
  {
    osId: "BD2021113R7R87P",
    name: "Zaber & Zubair Fabrics Ltd",
    address: "Pagar, Tongi, Gazipur, Dhaka",
    countryCode: "BD",
    countryName: "Bangladesh",
    lat: 23.896051,
    lng: 90.418952,
    sectors: ["Textile", "Apparel"],
    productTypes: ["Fabric"],
    claimed: true,
  },
  {
    osId: "CN202031463D4MB",
    name: "1010 Printing International Ltd",
    address: "Xia Nan Industry, Hui Xing Road, Yuanzhou Town",
    countryCode: "CN",
    countryName: "China",
    lat: 23.1259237,
    lng: 113.9573319,
    sectors: ["Apparel"],
    productTypes: [],
    claimed: false,
  },
  row("Shahi Exports Pvt Ltd", "Bengaluru, Karnataka", "IN", "India", ["Apparel"]),
  row("Gokaldas Exports", "Bengaluru, Karnataka", "IN", "India", ["Apparel"]),
  row("Arvind Limited", "Ahmedabad, Gujarat", "IN", "India", ["Textile", "Apparel"]),
  row("Welspun India", "Anjar, Gujarat", "IN", "India", ["Textile"]),
  row("Raymond UCO Denim", "Yavatmal, Maharashtra", "IN", "India", ["Textile"]),
  row("Kitex Garments", "Kizhakkambalam, Kerala", "IN", "India", ["Apparel"]),
  row("Eastman Exports", "Tiruppur, Tamil Nadu", "IN", "India", ["Apparel"]),
  row("Ha-Meem Group", "Tongi, Gazipur", "BD", "Bangladesh", ["Apparel"]),
  row("DBL Group", "Kashimpur, Gazipur", "BD", "Bangladesh", ["Apparel", "Textile"]),
  row("Ananta Companies", "Ashulia, Dhaka", "BD", "Bangladesh", ["Apparel"]),
  row("Square Fashions", "Kaliakoir, Gazipur", "BD", "Bangladesh", ["Apparel"]),
  row("Fakir Apparels", "Fatullah, Narayanganj", "BD", "Bangladesh", ["Apparel"]),
  row("Youngone Corporation — Chittagong", "Chattogram", "BD", "Bangladesh", ["Apparel", "Footwear"]),
  row("Epyllion Group", "Mirpur, Dhaka", "BD", "Bangladesh", ["Apparel"]),
  row("Palmal Group", "Savar, Dhaka", "BD", "Bangladesh", ["Apparel"]),
  row("Crystal International Group", "Dongguan, Guangdong", "CN", "China", ["Apparel"]),
  row("Esquel Group — Gaoming mill", "Foshan, Guangdong", "CN", "China", ["Textile", "Apparel"]),
  row("Makalot Industrial", "Taipei", "TW", "Taiwan", ["Apparel"]),
  row("TAL Apparel", "Hong Kong", "HK", "Hong Kong", ["Apparel"]),
  row("Makalot Vietnam", "Binh Duong", "VN", "Vietnam", ["Apparel"]),
  row("Sabrina Fashion Industrial Corp", "Ho Chi Minh City", "VN", "Vietnam", ["Apparel"]),
  row("Pou Chen Corporation", "Taichung", "TW", "Taiwan", ["Footwear"]),
  row("Yue Yuen Industrial", "Dongguan, Guangdong", "CN", "China", ["Footwear"]),
  row("MAS Holdings — Silueta", "Thulhiriya", "LK", "Sri Lanka", ["Apparel"]),
  row("Brandix Apparel", "Seeduwa", "LK", "Sri Lanka", ["Apparel"]),
  row("Hirdaramani Group", "Maharagama", "LK", "Sri Lanka", ["Apparel"]),
  row("Hela Clothing", "Katunayake", "LK", "Sri Lanka", ["Apparel"]),
  row("Aksa Akrilik", "Yalova", "TR", "Türkiye", ["Textile"]),
  row("Sanko Tekstil", "Gaziantep", "TR", "Türkiye", ["Textile"]),
  row("Bossa Denim", "Adana", "TR", "Türkiye", ["Textile"]),
  row("Isko Denim", "Kahramanmaraş", "TR", "Türkiye", ["Textile"]),
  row("Kipaş Textiles", "Kahramanmaraş", "TR", "Türkiye", ["Textile"]),
  row("Riopele Têxteis", "Pousada de Saramagos", "PT", "Portugal", ["Textile"]),
  row("Paulo de Oliveira", "Covilhã", "PT", "Portugal", ["Textile"]),
  row("Somelos", "Vizela", "PT", "Portugal", ["Textile"]),
  row("Lameirinho", "Guimarães", "PT", "Portugal", ["Textile"]),
  row("Impetus Portugal Têxteis", "Barcelos", "PT", "Portugal", ["Apparel", "Textile"]),
  row("Têxteis Penedo", "Guimarães", "PT", "Portugal", ["Textile"]),
  row("Fitecom", "Vila Nova de Famalicão", "PT", "Portugal", ["Textile"]),
  row("Marzotto Wool Manufacturing", "Valdagno", "IT", "Italy", ["Textile"]),
  row("Reda 1865", "Valle Mosso", "IT", "Italy", ["Textile"]),
  row("Vitale Barberis Canonico", "Pratrivero", "IT", "Italy", ["Textile"]),
  row("Albini Group", "Albino", "IT", "Italy", ["Textile"]),
  row("Canclini Tessile", "Cucciago", "IT", "Italy", ["Textile"]),
  row("John Smedley", "Lea Mills, Derbyshire", "GB", "United Kingdom", ["Apparel", "Textile"]),
  row("Abraham Moon & Sons", "Guiseley, West Yorkshire", "GB", "United Kingdom", ["Textile"]),
  row("Johnstons of Elgin", "Elgin, Moray", "GB", "United Kingdom", ["Textile"]),
  row("Begg x Co", "Paisley", "GB", "United Kingdom", ["Textile"]),
  row("AW Hainsworth", "Pudsey, West Yorkshire", "GB", "United Kingdom", ["Textile"]),
  row("Pincroft Dyeing & Printing", "Adlington, Lancashire", "GB", "United Kingdom", ["Textile"]),
  row("Nishat Mills", "Faisalabad", "PK", "Pakistan", ["Textile", "Apparel"]),
  row("Gul Ahmed Textile Mills", "Karachi", "PK", "Pakistan", ["Textile"]),
  row("Sapphire Textile Mills", "Lahore", "PK", "Pakistan", ["Textile"]),
  row("Artistic Milliners", "Karachi", "PK", "Pakistan", ["Textile", "Apparel"]),
  row("Style Textile", "Lahore", "PK", "Pakistan", ["Apparel"]),
  row("Saitex International", "Dong Nai", "VN", "Vietnam", ["Apparel"]),
  row("Hansae Vietnam", "Tay Ninh", "VN", "Vietnam", ["Apparel"]),
  row("Regina Miracle International", "Hai Phong", "VN", "Vietnam", ["Apparel"]),
  row("Gain Lucky Vietnam", "Binh Duong", "VN", "Vietnam", ["Apparel"]),
  row("Noman Group", "Savar, Dhaka", "BD", "Bangladesh", ["Apparel"]),
  row("Durdane", "Gaziantep", "TR", "Türkiye", ["Textile"]),
  row("Kipas Holding — denim", "Kahramanmaraş", "TR", "Türkiye", ["Textile"]),
  row("Sanko Park textile campus", "Gaziantep", "TR", "Türkiye", ["Textile"]),
  row("Tejidos Royo", "Alcoy", "ES", "Spain", ["Textile"]),
  row("Textil Santanderina", "Cabezón de la Sal", "ES", "Spain", ["Textile"]),
  row("Tavsancil Textiles", "Çorlu", "TR", "Türkiye", ["Textile"]),
  row("Evergreen Group — Formosa Taffeta", "Douliu", "TW", "Taiwan", ["Textile"]),
  row("Toray Textiles Europe", "Mansfield", "GB", "United Kingdom", ["Textile"]),
  row("Klopman International", "Frosinone", "IT", "Italy", ["Textile"]),
  row("UCO Fabrics", "Ghent", "BE", "Belgium", ["Textile"]),
  row("Concordia Textiles", "Waregem", "BE", "Belgium", ["Textile"]),
  row("Sioen Apparel", "Ardooie", "BE", "Belgium", ["Apparel"]),
  row("Delta Galil Industries", "Karmiel", "IL", "Israel", ["Apparel"]),
  row("Gildan Activewear — Honduras", "Choloma", "HN", "Honduras", ["Apparel"]),
  row("Fruit of the Loom — Honduras", "San Pedro Sula", "HN", "Honduras", ["Apparel"]),
  row("Hanesbrands — El Salvador", "San Salvador", "SV", "El Salvador", ["Apparel"]),
  row("SAQ — Casablanca knit", "Casablanca", "MA", "Morocco", ["Apparel"]),
  row("Fruit of the Loom — Morocco", "Sale", "MA", "Morocco", ["Apparel"]),
  row("Denim Authority", "Nabeul", "TN", "Tunisia", ["Textile", "Apparel"]),
  row("VF Jeanswear — Morocco", "Tangier", "MA", "Morocco", ["Apparel"]),
  row("PVH Farah — Sri Lanka", "Katunayake", "LK", "Sri Lanka", ["Apparel"]),
  row("Esquel Mauritius", "Terre Rouge", "MU", "Mauritius", ["Apparel"]),
  row("CIEL Textile — Tropic Knits", "Terre Rouge", "MU", "Mauritius", ["Apparel", "Textile"]),
  row("Aquarelle Clothing", "Riche Terre", "MU", "Mauritius", ["Apparel"]),
  row("Ethio-Japanese Textile", "Dukem", "ET", "Ethiopia", ["Textile"]),
  row("PVH Ethiopia — Hawassa", "Hawassa", "ET", "Ethiopia", ["Apparel"]),
  row("Hela Indochine", "Phnom Penh", "KH", "Cambodia", ["Apparel"]),
  row("Yakjin Trading — Cambodia", "Kampong Chhnang", "KH", "Cambodia", ["Apparel"]),
  row("Can Sports Cambodia", "Kampong Speu", "KH", "Cambodia", ["Footwear"]),
  row("Pou Chen Vietnam", "Dong Nai", "VN", "Vietnam", ["Footwear"]),
  row("Feng Tay Enterprises", "Yunlin", "TW", "Taiwan", ["Footwear"]),
  row("Kurabo Industries", "Osaka", "JP", "Japan", ["Textile"]),
  row("Toyobo Textile", "Osaka", "JP", "Japan", ["Textile"]),
  row("Hyosung TNC", "Seoul", "KR", "South Korea", ["Textile"]),
  row("Kolon Industries", "Gwacheon", "KR", "South Korea", ["Textile"]),
  row("Texhong Textile", "Hai Phong", "VN", "Vietnam", ["Textile"]),
  row("Pacific Textiles", "Hong Kong", "HK", "Hong Kong", ["Textile"]),
  row("Fountain Set (Holdings)", "Hong Kong", "HK", "Hong Kong", ["Textile"]),
  row("Makalot Indonesia", "Jakarta", "ID", "Indonesia", ["Apparel"]),
  row("Pan Brothers", "Tangerang", "ID", "Indonesia", ["Apparel"]),
  row("Sri Rejeki Isman (Sritex)", "Sukoharjo", "ID", "Indonesia", ["Textile", "Apparel"]),
  row("Busana Apparel Group", "Semarang", "ID", "Indonesia", ["Apparel"]),
  row("DBL Knitting", "Gazipur", "BD", "Bangladesh", ["Apparel"]),
  row("Premier Fashions", "Tiruppur", "IN", "India", ["Apparel"]),
  row("SCM Garments", "Tiruppur", "IN", "India", ["Apparel"]),
  row("KPR Mill", "Coimbatore", "IN", "India", ["Textile", "Apparel"]),
  row("Trident Limited", "Sanghera, Punjab", "IN", "India", ["Textile"]),
  row("Vardhman Textiles", "Ludhiana, Punjab", "IN", "India", ["Textile"]),
  row("Indorama Yarn", "Jakarta", "ID", "Indonesia", ["Textile"]),
  row("Lenzing — Heiligenkreuz", "Heiligenkreuz", "AT", "Austria", ["Textile"]),
  row("Lenzing — Mobile", "Mobile, Alabama", "US", "United States", ["Textile"]),
  row("Cone Denim — White Oak heritage", "Greensboro, North Carolina", "US", "United States", ["Textile"]),
  row("Parkdale Mills", "Gastonia, North Carolina", "US", "United States", ["Textile"]),
  row("Milliken & Company", "Spartanburg, South Carolina", "US", "United States", ["Textile"]),
  row("Polartec", "Lawrence, Massachusetts", "US", "United States", ["Textile"]),
  row("Vicunha Textil", "Americana, São Paulo", "BR", "Brazil", ["Textile"]),
  row("Santista Textil", "São Paulo", "BR", "Brazil", ["Textile"]),
  row("Tavex Brazil", "Montes Claros", "BR", "Brazil", ["Textile"]),
  row("Creditex", "Lima", "PE", "Peru", ["Textile"]),
  row("Textil del Valle", "Lima", "PE", "Peru", ["Apparel", "Textile"]),
  row("Cotton Knit Peru", "Lima", "PE", "Peru", ["Apparel"]),
  row("Aunde Group — Romania", "Sibiu", "RO", "Romania", ["Textile"]),
];

function row(
  name: string,
  address: string,
  countryCode: string,
  countryName: string,
  sectors: string[],
): OriginFacility {
  return {
    osId: "",
    name,
    address,
    countryCode,
    countryName,
    lat: null,
    lng: null,
    sectors,
    productTypes: [],
    claimed: false,
  };
}
